@startuml  サイト追加
title サイト追加

' アクター定義
actor "ユーザ" as user
participant "クライアント端末\n(PCまたはスマホ)" as device
participant "Webサーバ" as site
participant "認証基盤\n(Cognito)" as cognito
participant "CDN\n(CloudFront)" as cdn
participant "SPA資材格納\n(S3)" as spa
participant "SonicHost API\n(API-Gateway)" as api


user -> device ++: HOME画面表示
rnote right of device #GreenYellow
    ログインフローを参照
end note
user -> device : サイト追加選択

device -> device : プラン選択画面表示
device -> api ++ : プラン情報取得API
device <-- api -- : プラン情報
user -> device : プラン選択
device -> api ++ : プラン登録API
device <-- api -- 
alt カード情報未入力の場合
    device -> device : カード登録画面表示：Stripe
    user -> device : カード情報入力
    device -> api ++ : stripeAPI
    device <-- api -- 
    device -> device : 登録完了画面表示
    user -> device : 「サイト情報登録」押下
end 
device -> device : サイト名入力画面表示
user -> device : サイト名入力
device -> device : ドメイン方式選択画面表示
note right of device 
    ドメイン方式は以下から選択
    * 自分で取得したドメイン
    * Sonic Host提供のサブドメイン
    金額かえる？
    なら、カード入力のタイミング考慮要
end note
user -> device : ドメイン方式選択
alt 自前ドメイン方式の場合
    device -> device :ドメイン入力画面表示
    user -> device : ドメイン名入力
    user -> device : 「確定」押下
    device -> api ++ : ドメイン仮登録API
    device <-- api -- 
    device -> device : ネームサーバ表示画面
    user -> device : 確認
    user -> device : 「次へ」押下
else Sonic Hostサブドメイン方式の場合
    device -> api ++ : ドメイン一覧取得API
    device <-- api -- 
    device -> device : ドメイン選択・入力画面表示
    user -> device : ドメイン選択
    user -> device : サブドメイン入力
    user -> device : 「次へ」押下
end 
device -> device : サブドメインズ入力画面
user -> device : サイトドメイン入力
user -> device : メールドメイン入力
user -> device : 「確認」押下
device -> device : 入力内容確認画面表示
rnote right of device #SkyBlue
    変更したい項目があれば「変更」ボタンを押下。
    外套の変更画面に遷移し、「確認」ボタンを
    押下すると今の画面に戻る
end note
user -> device : 「確定」押下
device -> api ++ : サイト情報更新API
device <-- api -- 
alt サイト初回登録の場合
    device -> device : Welcome画面表示
    user -> device : 「Homeへ進む」押下
end 
device -> device : HOME画面表示

@enduml