@startuml パスワード忘れ
title パスワード忘れ


' アクター定義
actor "ユーザ" as user
participant "クライアント端末\n(PCまたはスマホ)" as device
participant "認証基盤\n(Cognito)" as cognito
participant "CDN\n(CloudFront)" as cdn
participant "SPA資材格納\n(S3)" as spa

' 起動
user -> device ++ : 管理画面起動
device -> cdn ++
cdn -> spa ++ : バンドル資材要求
cdn <-- spa --
device <-- cdn --
device ->device : バンドル資材読み込み
device -> device: トークンチェック
' トークンチェック
rnote right of device #Orange
    トークンチェック失敗
end note
device -> device : ログイン画面表示
' パスワードリマインダフロー
user -> device : 「パスワードを忘れた場合はこちら」\nをクリック
device -> device : パスワードリマインダ画面を表示
user -> device : メールアドレス入力
user -> device : 確認押下
device -> cognito ++ : パスワードリマインダAPI
cognito -> user : メール送信
device <-- cognito --
user -> device ++ : メールからリンクを押下\n新規ブラウザ
device -> device : パスワードリセット画面開く\nCognito提供
user -> device : 検証コードと新パスワード入力
user -> device : 確認押下
device -> cognito ++ : パスワードリセットAPI
cognito -> cognito : パスワード更新
device <-- cognito -- 
device -> device : 完了画面表示
user -> device : タブを閉じる
deactivate device

user -> device : SonicHostを開く
device -> device : ログイン画面を開く
user -> device : 新パスワードを入力

@enduml