@startuml ログイン
title ログイン


' アクター定義
actor "ユーザ" as user
participant "クライアント端末\n(PCまたはスマホ)" as device
participant "認証基盤\n(Cognito)" as cognito
participant "CDN\n(CloudFront)" as cdn
participant "SonicHost API\n(API-Gateway)" as api
participant "SPA資材格納\n(S3)" as spa
participant "静的コンテンツ格納\n(S3)" as static

' 起動
user -> device ++ : 管理画面起動
device -> cdn ++
cdn -> spa ++ : バンドル資材要求
cdn <-- spa --
device <- cdn --
device ->device : バンドル資材読み込み
device -> cognito ++ :  リフレッシュトークンフロー
device <-- cognito -- : トークン情報
device -> device : トークンチェック
' トークンチェック
alt トークン取得失敗 or トークンチェック失敗
    device -> device : ログイン画面表示
    alt パスワード忘れた場合
        user -> device : 「パスワードを忘れた場合はこちら」\nをクリック
        rnote right of device #GreenYellow
            パスワードリマインダフローを参照
        end note
    else 新規会員登録の場合
        user -> device: 「会員登録はこちら」\nをクリック
        rnote right of device #GreenYellow
            会員登録フローを参照
        end note
    end 
    device -> cognito ++ : ログイン確立要求\n(Initiate Auth)
    device <-- cognito -- : session等
    user -> device : ユーザ名・パスワード入力
    device -> cognito ++ : 認証(トークン発行依頼)\n(Responed to Auth Challenge)
    device -> cognito ++ : トークンチェック用公開鍵要求
    device <-- cognito --
    device <-- cognito -- : トークン
    device -> device : トークンチェック
end 
' 規約確認
rnote right of device #SkyBlue
    ログイン直後は以下のAPIを打鍵してグローバルな情報を取り込む
    * サイト一覧取得API
    * お知らせ一通知覧取得API
    * 利用規約ステータス取得API
end note 
device -> api ++ : サイト一覧取得API \n /site GET
device <-- api --
device -> device : LocalStorageより選択中のサイトを取得。
alt LocalStorageに選択中のサイトが存在　かつ　サイト一覧に該当のサイトがある場合
    device -> device : 選択中のサイトとして、\nLocalStorageに格納されていたサイトを設定
else LocalStorageに選択中のサイトがない。　もしくは　サイト一覧に該当のサイトがない場合。
    device -> device : 選択中のサイトとして、サイト一覧の一番最初のサイトを選択。
end
device -> api ++ : お知らせ通知一覧取得API \n /notifications GET
device <-- api -- 
device -> api ++ : 利用規約ステータス取得API \n /termStatus GET
rnote right of cdn #SkyBlue
    API-GWでCognitoのトークンチェックも実施する。
    1つだけ丁寧に記載するが、以降はトークンチェック等のシーケンスを省略
end note
api -> api : トークンチェック
api -> api : ユーザの規約情報を\nDynamoDBより取得
device <-- api --
device -> device : 元々表示しようとしていた画面を表示
alt 新規の規約未確認状態
    device -> device : 規約画面表示\n強制再同意
    device -> api ++ : 規約取得 \n /term GET \nドメインは公開ドメイン
    api -> static ++ 
    api <-- static --
    device <-- api --
    user -> device : 規約同意\nチェックボックス押下
    user -> device : 「確認した」ボタン押下
    device -> api ++ : 利用規約チェックステータス更新API \n /termStatus PUT
    device <-- api --
    device -> device : 規約画面を閉じる
end




@enduml