@startuml ログイン
title ログイン


' アクター定義
actor "ユーザ" as user
participant "クライアント端末\n(PCまたはスマホ)" as device
participant "認証基盤\n(Cognito)" as cognito
participant "CDN\n(CloudFront)" as cdn
participant "SonicHost API\n(API-Gateway)" as api
participant "SPA資材格納\n(S3)" as spa
participant "静的コンテンツ格納\n(S3)" as static

' 起動
user -> device ++ : 管理画面起動
device -> cdn ++
cdn -> spa ++ : バンドル資材要求
cdn <- spa --
device <- cdn --
device ->device : バンドル資材読み込み
device -> cognito ++ : トークンチェック用公開鍵要求
device <- cognito --
device -> device: トークンチェック
' トークンチェック
alt トークン取得失敗 or トークンチェック失敗
    device -> device : ログイン画面表示
    alt パスワード忘れた場合
        user -> device : 「パスワードを忘れた場合はこちら」\nをクリック
        rnote right of device #GreenYellow
            パスワードリマインダフローを参照
        end note
    else 新規会員登録の場合
        user -> device: 「会員登録はこちら」\nをクリック
        rnote right of device #GreenYellow
            会員登録フローを参照
        end note
    end 
    device -> cognito ++ : ログイン確立要求\n(Initiate Auth)
    device <-- cognito -- : session等
    user -> device : ユーザ名・パスワード入力
    device -> cognito ++ : 認証(トークン発行依頼)\n(Responed to Auth Challenge)
    device -> cognito ++ : トークンチェック用公開鍵要求
    device <- cognito --
    device <-- cognito -- : トークン
    device -> device : トークンチェック
end 
' 規約確認
rnote right of device #SkyBlue
    ログイン直後は以下のAPIを打鍵してグローバルな情報を取り込む
    * ユーザ情報取得API
    * サイト情報取得API
end note 
device -> cdn ++ : ユーザ情報取得API
cdn -> api ++ 
cdn <- api --
device <- cdn --
device -> cdn ++ : サイト情報取得API
cdn -> api ++
cdn <- api --
device <- cdn -- 
device -> cdn ++ : 規約チェックAPI
cdn -> api ++
rnote right of cdn #SkyBlue
    CORS回避のため、API打鍵はCloudFrontを通す
    また、API-GWでCognitoのトークンチェックも実施する。
    1つだけ丁寧に記載するが、以降はトークンチェック等のシーケンスを省略
end note
api -> api : トークンチェック
api -> api : ユーザの規約\n状態を確認
cdn <- api --
device <- cdn --
device -> device : 元々表示しようとしていた画面を表示
alt 新規の規約未確認状態
    device -> device : 規約画面表示\n全画面モーダル
    device -> cdn ++ : 規約情報取得
    cdn -> static ++ 
    cdn <- static --
    device <- cdn --
    user -> device : 規約同意\nチェックボックス押下
    user -> device : 「確認した」ボタン押下
    device -> cdn ++ : 規約同意日時更新API
    cdn -> api ++ 
    cdn <- api --
    device <- cdn --
    device -> device : 規約画面のモーダルを閉じる
end




@enduml