@startuml ブログアップロード
title ブログアップロード


' アクター定義
actor "ユーザ" as user
participant "クライアント端末\n(PCまたはスマホ)" as device
participant "認証基盤\n(Cognito)" as cognito
participant "CDN\n(CloudFront)" as cdn
participant "WordPress管理バケット\n(S3)" as s3
participant "SonicHost API\n(API-Gateway)" as api

user -> device ++ : HOME画面を起動
rnote right of device #GreenYellow
    ログインフローを参照
end note
device -> device : HOME画面を表示
user -> device : ドラッグ＆ドロップ　or ファイル選択\n WordPressのBackUpファイル
device -> cdn ++ : アップロード用一時認証取得API
cdn -> api ++ 
cdn <-- api --
device <-- cdn -- : STS取得
device -> s3 ++ : WordPressのバックアップファイルをアップロード
s3 -> s3 : 資材保管\nサイトドメインごとにキーを設定
device <-- s3 --
device -> device : アップロード完了モーダル表示
user -> device : 「OK」押下
device -> device : モーダル閉じる
rnote right of device #GreenYellow
    続きのバッチ処理は
    ブログ生成フローを参照
end note



@enduml