@startuml  パスワード変更
title パスワード変更

' アクター定義
actor "ユーザ" as user
participant "クライアント端末\n(PCまたはスマホ)" as device
participant "認証基盤\n(Cognito)" as cognito

user -> device ++: HOME画面表示
rnote right of device #GreenYellow
    ログインフローを参照
end note
user -> device : ユーザアイコン押下
device -> device : ユーザメニューを表示
user -> device : セキュリティ確認を押下
device -> device : セキュリティ設定画面を表示
user -> device : パスワード変更を押下
device -> device : パスワード変更画面を表示
user -> device : ユーザ名\n旧パスワード/新パスワード入力
user -> device : パスワード変更押下
device -> cognito ++ : パスワード変更API打鍵
device <-- cognito --
device -> device : パスワード変更完了画面表示
user -> device : 確認完了押下
device -> device : トークン削除
device -> device : ログイン画面表示
